// Comprehensive search index for Brainopedia
// Each entry maps to a route in ArticleContent
// Sub-page entries use breadcrumb-style labels so users know exactly where they're going

export interface SearchEntry {
  id: string;
  label: string;
  keywords: string;
}

export const searchableArticles: SearchEntry[] = [
  // ============================================================
  // HOME & UTILITY PAGES
  // ============================================================
  { id: 'about', label: 'Home & About', keywords: 'brainopedia home about neurodivergent welcome introduction what is neurodivergence conditions overview encyclopedia guide resource information help support understanding brain differences' },
  { id: 'blog', label: 'Blog & Updates', keywords: 'blog news updates articles posts latest new content announcements community stories' },
  { id: 'donate', label: 'Donate', keywords: 'donate support contribute funding help sponsor patron give back financial assistance charity nonprofit mission volunteer' },

  // ============================================================
  // ADHD - Main + Sub-pages
  // ============================================================
  { id: 'adhd', label: 'ADHD', keywords: 'attention deficit hyperactivity disorder adhd add inattention impulsivity executive function focus concentration distracted forgetful procrastination time blind hyperfocus fidgeting restless medication stimulant adderall ritalin vyvanse concerta executive dysfunction working memory dopamine brain fog scatter brained zoning out daydreaming disorganized losing things impulsive interrupting blurting out hyperactive motivation reward seeking boredom understimulated overstimulated emotional dysregulation rejection sensitive rsd meltdown burnout masking coping strategies accommodations 504 iep school work productivity planning organizing time management routine structure habits' },
  { id: 'adhd-overview', label: 'ADHD \u2192 Overview', keywords: 'adhd overview introduction what is attention deficit hyperactivity disorder history prevalence types presentations inattentive hyperactive combined predominantly neurodevelopmental brain disorder executive function dopamine norepinephrine neurotransmitter lifespan chronic persistent' },
  { id: 'adhd-symptoms', label: 'ADHD \u2192 Symptoms', keywords: 'adhd symptoms signs inattention hyperactivity impulsivity executive dysfunction cant focus trouble concentrating forgetful losing things disorganized careless mistakes daydreaming zoning out fidgeting restless cant sit still interrupting blurting out impatient talking excessively running climbing driven by motor emotional dysregulation rejection sensitive dysphoria rsd mood swings frustration low tolerance anger outbursts meltdown time blindness hyperfocus women girls female presentation masking internalized anxiety depression myths misconceptions lazy stupid not trying hard enough just need to focus' },
  { id: 'adhd-causes', label: 'ADHD \u2192 Causes', keywords: 'adhd causes risk factors genetics hereditary heritability genes dopamine neurotransmitter brain structure development prefrontal cortex basal ganglia neurobiology neuroimaging fmri brain scan environmental factors prenatal exposure smoking alcohol lead toxins premature birth low birth weight pregnancy complications epigenetics gene environment interaction not caused by bad parenting sugar screen time' },
  { id: 'adhd-diagnosis', label: 'ADHD \u2192 Diagnosis', keywords: 'adhd diagnosis assessment evaluation testing screening dsm criteria diagnostic how to get diagnosed who diagnoses psychiatrist psychologist neuropsychologist pediatrician rating scales conners vanderbilt clinical interview history childhood symptoms adult diagnosis late diagnosis women girls missed diagnosis misdiagnosis differential diagnosis comorbid conditions anxiety depression bipolar learning disability autism' },
  { id: 'adhd-support', label: 'ADHD \u2192 Support & Treatment', keywords: 'adhd support treatment therapy medication stimulant nonstimulant adderall ritalin vyvanse concerta strattera wellbutrin intuniv guanfacine behavioral therapy cbt cognitive behavioral therapy coaching adhd coach psychoeducation parent training classroom accommodations iep 504 plan workplace accommodations ada multimodal treatment combination therapy' },
  { id: 'adhd-living', label: 'ADHD \u2192 Living with ADHD', keywords: 'adhd living daily life coping strategies tips tricks hacks organization planning time management routines habits productivity apps tools systems bullet journal planner timer pomodoro body doubling accountability partner exercise nutrition sleep hygiene mindfulness meditation self care relationships communication parenting marriage dating self esteem confidence identity strengths creativity entrepreneurship thriving success stories adults children teens college' },

  // ============================================================
  // AUTISM (ASD) - Main + Sub-pages
  // ============================================================
  { id: 'autism', label: 'Autism (ASD)', keywords: 'autism spectrum disorder asd asperger social communication sensory repetitive behaviors neurodevelopmental stimming meltdown shutdown masking camouflaging eye contact nonverbal body language tone voice literal thinking special interest routine change transition anxiety overwhelmed overstimulated sensory overload alexithymia echolalia selective mutism autistic burnout demand avoidance pda diagnosis late diagnosis adult diagnosis women girls afab' },
  { id: 'autism-overview', label: 'Autism \u2192 Overview', keywords: 'autism overview introduction what is autism spectrum disorder asd history prevalence rates statistics increasing diagnosis neurodiversity movement identity first person first language spectrum concept support needs levels level 1 level 2 level 3 dsm icd classification neurodevelopmental lifespan condition not disease not illness strengths differences' },
  { id: 'autism-symptoms', label: 'Autism \u2192 Symptoms & Traits', keywords: 'autism symptoms signs traits characteristics social communication differences difficulty reading social cues eye contact facial expressions body language tone of voice sarcasm irony literal concrete thinking conversation reciprocity friendship relationships repetitive behaviors stimming hand flapping rocking spinning echolalia restricted interests special interests intense focused passionate routine sameness predictability change difficulty transitions meltdown shutdown sensory processing differences sensitivity noise light texture taste smell touch pain temperature interoception alexithymia emotions identifying expressing monotropism attention detail pattern recognition' },
  { id: 'autism-causes', label: 'Autism \u2192 Causes', keywords: 'autism causes risk factors genetics hereditary heritability genes chromosomes copy number variants de novo mutations polygenic brain development prenatal environment maternal immune activation infection inflammation advanced parental age pregnancy complications epigenetics gene expression neuroanatomy brain connectivity pruning synapse formation not caused by vaccines not caused by parenting not caused by refrigerator mother debunked myths' },
  { id: 'autism-diagnosis', label: 'Autism \u2192 Diagnosis', keywords: 'autism diagnosis assessment evaluation screening how to get diagnosed who diagnoses developmental pediatrician neuropsychologist psychiatrist psychologist ados adi clinical observation dsm criteria diagnostic criteria social communication restricted repetitive behaviors sensory early signs toddler infant developmental milestones late diagnosis adult diagnosis women girls masking camouflaging missed diagnosis misdiagnosis anxiety depression ocd eating disorder personality disorder differential diagnosis self diagnosis' },
  { id: 'autism-support', label: 'Autism \u2192 Support & Therapies', keywords: 'autism support treatment therapy intervention early intervention therapies evidence based aba applied behavior analysis speech therapy occupational therapy social skills training cbt cognitive behavioral therapy sensory integration medication anxiety depression sleep melatonin risperidone aripiprazole accommodations school workplace iep 504 individualized education plan structured teaching teacch visual supports social stories' },
  { id: 'autism-living', label: 'Autism \u2192 Living with Autism', keywords: 'autism living daily life coping strategies sensory management routine structure predictability visual schedule social navigation relationships friendships dating marriage parenting employment workplace accommodations independent living self advocacy self care meltdown prevention recovery burnout prevention energy management spoon theory battery metaphor regulation co-regulation calming strategies safe space decompression special interests strengths identity neurodiversity acceptance thriving adults children teens transition adulthood' },
  { id: 'autism-speech-therapy', label: 'Autism \u2192 Speech Therapy', keywords: 'autism speech therapy language communication verbal nonverbal aac augmentative alternative communication speech language pathologist slp articulation expressive receptive pragmatic social communication picture exchange pecs sign language communication device tablet app echolalia gestalt language processing' },
  { id: 'autism-occupational-therapy', label: 'Autism \u2192 Occupational Therapy', keywords: 'autism occupational therapy ot sensory integration sensory diet fine motor gross motor handwriting daily living skills self care dressing eating bathing grooming adaptive skills independence regulation sensory processing weighted blanket compression therapy swing brushing protocol wilbarger body awareness proprioception vestibular' },
  { id: 'autism-aba-therapy', label: 'Autism \u2192 ABA Therapy', keywords: 'autism aba applied behavior analysis therapy behavioral intervention discrete trial training natural environment teaching reinforcement positive behavior support functional behavior assessment antecedent behavior consequence prompting shaping chaining task analysis controversy criticism ethics consent neurodiversity perspective reform modern aba' },
  { id: 'autism-social-skills', label: 'Autism \u2192 Social Skills', keywords: 'autism social skills training group therapy friendship making friends keeping friends conversation turn taking perspective taking theory of mind empathy reading social cues body language facial expressions tone sarcasm humor idioms figures of speech social stories comic strip conversations video modeling role playing peer mentoring social thinking' },
  { id: 'autism-mental-health', label: 'Autism \u2192 Mental Health', keywords: 'autism mental health anxiety depression suicidal ideation self harm burnout autistic burnout exhaustion emotional regulation meltdown shutdown trauma ptsd adverse experiences bullying masking camouflaging toll cost identity crisis self esteem self worth belonging acceptance therapy counseling cbt dbt mindfulness adapted therapy autistic therapist neurodiversity affirming' },

  // ============================================================
  // DYSLEXIA - Main + Sub-pages
  // ============================================================
  { id: 'dyslexia', label: 'Dyslexia', keywords: 'dyslexia reading learning disability phonological decoding literacy letters words spelling trouble reading slow reader mixing up letters reversing letters reading comprehension fluency phonics orton gillingham audiobook assistive technology accommodation school iep 504 tutoring' },
  { id: 'dyslexia-overview', label: 'Dyslexia \u2192 Overview', keywords: 'dyslexia overview introduction what is reading disability learning difference prevalence statistics history types phonological surface rapid naming double deficit deep dyslexia brain differences left hemisphere angular gyrus wernicke broca area neuroimaging strengths big picture thinking spatial reasoning creativity entrepreneurship' },
  { id: 'dyslexia-symptoms', label: 'Dyslexia \u2192 Symptoms', keywords: 'dyslexia symptoms signs trouble reading slow reading inaccurate decoding guessing words skipping words losing place mixing up letters reversing b d p q spelling errors inconsistent spelling phonological awareness rhyming syllables sounds poor fluency choppy reading reading avoidance fatigue headaches reading aloud embarrassment comprehension difficulty vocabulary word retrieval tip of tongue writing difficulties early signs preschool kindergarten elementary middle high school adult' },
  { id: 'dyslexia-causes', label: 'Dyslexia \u2192 Causes', keywords: 'dyslexia causes risk factors genetics hereditary heritability family history genes dcd1 dcd2 kiaa0319 robo1 brain differences neuroanatomy left hemisphere temporal parietal occipital phonological processing magnocellular theory cerebellar theory automaticity not caused by laziness not vision problem not intelligence' },
  { id: 'dyslexia-diagnosis', label: 'Dyslexia \u2192 Diagnosis', keywords: 'dyslexia diagnosis assessment evaluation testing screening how to get diagnosed psychoeducational evaluation neuropsychological testing reading assessment phonological awareness decoding fluency comprehension spelling iq discrepancy model response to intervention rti school evaluation private evaluation early identification kindergarten screening' },
  { id: 'dyslexia-support', label: 'Dyslexia \u2192 Support & Treatment', keywords: 'dyslexia support treatment intervention orton gillingham wilson reading lindamood bell barton reading program structured literacy multisensory teaching phonics explicit systematic instruction tutoring reading specialist assistive technology text to speech audiobook speech to text dictation accommodation extra time quiet room alternative testing iep 504 plan classroom modifications' },
  { id: 'dyslexia-living', label: 'Dyslexia \u2192 Living with Dyslexia', keywords: 'dyslexia living daily life coping strategies study tips reading strategies audiobooks ebooks text to speech technology tools apps organization note taking study skills self advocacy confidence self esteem identity strengths creativity big picture thinking spatial reasoning famous people with dyslexia success stories career workplace accommodations adults children teens college' },

  // ============================================================
  // DYSCALCULIA - Main + Sub-pages
  // ============================================================
  { id: 'dyscalculia', label: 'Dyscalculia', keywords: 'dyscalculia math mathematics number sense arithmetic learning disability calculation counting money time numbers trouble with math math anxiety fractions decimals algebra geometry word problems mental math calculator accommodation' },
  { id: 'dyscalculia-overview', label: 'Dyscalculia \u2192 Overview', keywords: 'dyscalculia overview introduction what is math learning disability prevalence statistics types developmental acquired brain number processing quantity subitizing number sense magnitude comparison' },
  { id: 'dyscalculia-symptoms', label: 'Dyscalculia \u2192 Symptoms', keywords: 'dyscalculia symptoms signs trouble counting number sense difficulty subitizing quantity comparison magnitude place value math facts memorization addition subtraction multiplication division fractions decimals percentages word problems money counting change telling time elapsed time measurement estimation spatial reasoning number line sequencing steps procedures formulas math anxiety avoidance finger counting' },
  { id: 'dyscalculia-causes', label: 'Dyscalculia \u2192 Causes', keywords: 'dyscalculia causes risk factors genetics brain intraparietal sulcus number processing prefrontal cortex working memory neuroimaging hereditary family history premature birth low birth weight turner syndrome fragile x fetal alcohol' },
  { id: 'dyscalculia-diagnosis', label: 'Dyscalculia \u2192 Diagnosis', keywords: 'dyscalculia diagnosis assessment evaluation testing screening math assessment achievement test psychoeducational neuropsychological keymath woodcock johnson wiat number sense screening early identification response to intervention school evaluation private evaluation' },
  { id: 'dyscalculia-support', label: 'Dyscalculia \u2192 Support & Treatment', keywords: 'dyscalculia support treatment intervention math instruction multisensory concrete manipulatives visual models number line ten frames base ten blocks cuisenaire rods tutoring math specialist explicit instruction scaffolding calculator accommodation extra time iep 504 classroom modifications technology apps games' },
  { id: 'dyscalculia-living', label: 'Dyscalculia \u2192 Living with Dyscalculia', keywords: 'dyscalculia living daily life coping strategies money management budgeting calculator app shopping cooking measuring time management scheduling tips tools technology adults children teens workplace accommodations career self advocacy confidence self esteem' },

  // ============================================================
  // DYSGRAPHIA - Main + Sub-pages
  // ============================================================
  { id: 'dysgraphia', label: 'Dysgraphia', keywords: 'dysgraphia writing handwriting motor learning disability spelling fine motor messy handwriting illegible writing slow writer trouble writing essay paragraph sentences grammar punctuation pencil grip hand pain typing keyboard assistive technology speech to text accommodation occupational therapy' },
  { id: 'dysgraphia-overview', label: 'Dysgraphia \u2192 Overview', keywords: 'dysgraphia overview introduction what is writing disability learning difference types dyslexic motor spatial prevalence handwriting legibility fine motor skills written expression' },
  { id: 'dysgraphia-symptoms', label: 'Dysgraphia \u2192 Symptoms', keywords: 'dysgraphia symptoms signs messy handwriting illegible inconsistent letter size spacing formation slow writing hand pain fatigue cramping awkward pencil grip pressure too hard too light mixing print cursive trouble staying on lines margins spacing words organization ideas paper written expression difficulty spelling errors grammar punctuation avoidance refuses to write short answers incomplete assignments' },
  { id: 'dysgraphia-causes', label: 'Dysgraphia \u2192 Causes', keywords: 'dysgraphia causes risk factors fine motor development motor planning orthographic coding working memory language processing brain parietal lobe frontal lobe genetics hereditary co-occurring conditions adhd dyslexia autism developmental coordination disorder' },
  { id: 'dysgraphia-diagnosis', label: 'Dysgraphia \u2192 Diagnosis', keywords: 'dysgraphia diagnosis assessment evaluation testing handwriting assessment writing sample analysis occupational therapy evaluation fine motor assessment psychoeducational neuropsychological beery vmi tat school evaluation who diagnoses' },
  { id: 'dysgraphia-support', label: 'Dysgraphia \u2192 Support & Treatment', keywords: 'dysgraphia support treatment intervention occupational therapy handwriting instruction handwriting without tears fine motor exercises pencil grip adaptive grip assistive technology typing keyboard word processor speech to text dictation graphic organizers accommodation extra time reduced writing alternative assignments scribe note taker iep 504' },
  { id: 'dysgraphia-living', label: 'Dysgraphia \u2192 Living with Dysgraphia', keywords: 'dysgraphia living daily life coping strategies technology tools typing keyboard tablet stylus speech to text voice dictation note taking apps graphic organizers self advocacy confidence self esteem workplace accommodations career adults children teens college' },

  // ============================================================
  // NVLD - Main + Sub-pages
  // ============================================================
  { id: 'nvld', label: 'Non-Verbal Learning Disability (NVLD)', keywords: 'nvld nonverbal non-verbal learning disability spatial visual social skills math geometry map directions navigation body language facial expressions tone of voice sarcasm abstract thinking motor coordination clumsy' },
  { id: 'nvld-overview', label: 'NVLD \u2192 Overview', keywords: 'nvld overview introduction what is nonverbal learning disability profile verbal strengths visual spatial weaknesses social perception motor coordination right hemisphere white matter prevalence recognition controversy' },
  { id: 'nvld-symptoms', label: 'NVLD \u2192 Symptoms', keywords: 'nvld symptoms signs visual spatial difficulties math geometry map reading directions getting lost poor coordination clumsy awkward handwriting social difficulties reading body language facial expressions tone of voice sarcasm irony nonliteral language abstract thinking big picture detail focused verbal strengths vocabulary reading decoding' },
  { id: 'nvld-causes', label: 'NVLD \u2192 Causes', keywords: 'nvld causes risk factors brain white matter right hemisphere development genetics neurological' },
  { id: 'nvld-diagnosis', label: 'NVLD \u2192 Diagnosis', keywords: 'nvld diagnosis assessment evaluation testing neuropsychological iq verbal performance discrepancy visual spatial processing social perception motor skills who diagnoses recognition challenges dsm not listed' },
  { id: 'nvld-support', label: 'NVLD \u2192 Support & Treatment', keywords: 'nvld support treatment intervention social skills training occupational therapy visual spatial training cognitive behavioral therapy explicit instruction direct teaching social cues accommodation school workplace iep 504' },
  { id: 'nvld-living', label: 'NVLD \u2192 Living with NVLD', keywords: 'nvld living daily life coping strategies navigation gps directions social strategies verbal mediation self talk explicit rules organization routine strengths verbal abilities reading writing vocabulary self advocacy adults children teens' },

  // ============================================================
  // DLD - Main + Sub-pages
  // ============================================================
  { id: 'dld', label: 'Developmental Language Disorder (DLD)', keywords: 'dld developmental language disorder speech communication grammar vocabulary language delay slow talker late talker trouble speaking understanding directions receptive expressive speech therapy' },
  { id: 'dld-overview', label: 'DLD \u2192 Overview', keywords: 'dld overview introduction what is developmental language disorder prevalence statistics formerly specific language impairment sli language processing receptive expressive persistent hidden disability' },
  { id: 'dld-symptoms', label: 'DLD \u2192 Symptoms', keywords: 'dld symptoms signs late talking limited vocabulary short sentences grammar errors word finding difficulty understanding complex instructions following directions conversation difficulty storytelling narrative reading comprehension written expression social communication academic impact' },
  { id: 'dld-causes', label: 'DLD \u2192 Causes', keywords: 'dld causes risk factors genetics hereditary family history brain language areas processing neurobiological not caused by bilingualism not laziness not intelligence' },
  { id: 'dld-diagnosis', label: 'DLD \u2192 Diagnosis', keywords: 'dld diagnosis assessment evaluation testing speech language pathologist slp standardized tests language sample analysis receptive expressive vocabulary grammar narrative clinical evaluation school evaluation early identification' },
  { id: 'dld-support', label: 'DLD \u2192 Support & Treatment', keywords: 'dld support treatment intervention speech therapy language therapy slp individual group classroom vocabulary building grammar instruction narrative language comprehension strategies visual supports graphic organizers accommodation school iep 504 modified language simplified instructions' },
  { id: 'dld-living', label: 'DLD \u2192 Living with DLD', keywords: 'dld living daily life coping strategies communication strategies self advocacy social skills relationships confidence self esteem academic support workplace accommodations career adults children teens awareness understanding' },

  // ============================================================
  // HYPERLEXIA - Main + Sub-pages
  // ============================================================
  { id: 'hyperlexia', label: 'Hyperlexia', keywords: 'hyperlexia early reading advanced decoding comprehension precocious self taught reader reading before age gifted reads early fascinated letters words numbers autism spectrum language delay' },
  { id: 'hyperlexia-overview', label: 'Hyperlexia \u2192 Overview', keywords: 'hyperlexia overview introduction what is types type 1 2 3 early precocious reading decoding advanced word recognition fascination print letters numbers autism associated neurotypical gifted' },
  { id: 'hyperlexia-symptoms', label: 'Hyperlexia \u2192 Symptoms', keywords: 'hyperlexia symptoms signs self taught reading before age 3 4 5 fascination letters words numbers print logos signs intense interest decoding far above age level comprehension gap reads but doesnt understand literal concrete social communication differences language delay echolalia' },
  { id: 'hyperlexia-causes', label: 'Hyperlexia \u2192 Causes', keywords: 'hyperlexia causes risk factors brain visual processing word recognition language neurodevelopmental autism connection splinter skill pattern recognition' },
  { id: 'hyperlexia-diagnosis', label: 'Hyperlexia \u2192 Diagnosis', keywords: 'hyperlexia diagnosis assessment evaluation advanced reading testing comprehension assessment speech language evaluation autism screening developmental pediatrician neuropsychologist differentiate from giftedness' },
  { id: 'hyperlexia-support', label: 'Hyperlexia \u2192 Support', keywords: 'hyperlexia support treatment intervention leverage reading strength comprehension instruction visual learner written instructions text based learning speech therapy language therapy social skills reading comprehension strategies' },
  { id: 'hyperlexia-living', label: 'Hyperlexia \u2192 Living with Hyperlexia', keywords: 'hyperlexia living daily life strengths reading ability visual learning written communication leverage interests comprehension building social development' },

  // ============================================================
  // GIFTEDNESS - Main + Sub-pages
  // ============================================================
  { id: 'giftedness', label: 'Giftedness', keywords: 'giftedness gifted talented high ability intelligence iq advanced intellectual smart bright genius prodigy bored unchallenged perfectionism anxiety overexcitability intense emotions sensitivity enrichment acceleration' },
  { id: 'giftedness-overview', label: 'Giftedness \u2192 Overview', keywords: 'giftedness overview introduction what is gifted definition iq threshold identification prevalence models theories renzulli three ring gagne differentiated columbus group profoundly gifted highly gifted moderately gifted intellectual creative artistic leadership domains multiple intelligences' },
  { id: 'giftedness-symptoms', label: 'Giftedness \u2192 Characteristics', keywords: 'giftedness symptoms characteristics traits signs rapid learning quick learner advanced vocabulary early reader intense curiosity questioning why how deep thinking abstract reasoning complex ideas pattern recognition perfectionism sensitivity overexcitability intellectual psychomotor sensual imaginational emotional dabrowski asynchronous development ahead in some areas behind in others social differences feeling different peers boredom frustration underachievement' },
  { id: 'giftedness-causes', label: 'Giftedness \u2192 Causes', keywords: 'giftedness causes origins genetics hereditary iq brain development neural efficiency processing speed environment enrichment nature nurture gene environment interaction' },
  { id: 'giftedness-diagnosis', label: 'Giftedness \u2192 Identification', keywords: 'giftedness diagnosis identification assessment testing iq test wisc stanford binet achievement test gifted screening teacher nomination parent nomination portfolio cognitive assessment cutoff score ceiling effect twice exceptional missed identification underrepresented minority low income equity access bias cultural linguistic diversity' },
  { id: 'giftedness-support', label: 'Giftedness \u2192 Support & Education', keywords: 'giftedness support education enrichment acceleration grade skipping subject acceleration compacting differentiation gifted program pull out cluster grouping mentorship independent study competitions olympiad honors ap ib dual enrollment college early entrance homeschool talent development counseling social emotional perfectionism existential' },
  { id: 'giftedness-living', label: 'Giftedness \u2192 Living with Giftedness', keywords: 'giftedness living daily life social emotional needs perfectionism coping imposter syndrome existential anxiety depression intensity overexcitability finding peers like minded community multipotentiality career purpose meaning relationships dating friendship adults gifted adults' },

  // ============================================================
  // TWICE EXCEPTIONAL (2E) - Main + Sub-pages
  // ============================================================
  { id: 'twice-exceptional', label: 'Twice Exceptional (2E)', keywords: 'twice exceptional 2e gifted disability dual exceptionality smart but struggling gifted with adhd gifted with autism gifted with dyslexia paradox strengths weaknesses uneven profile asynchronous misunderstood underachieving masking compensating' },
  { id: 'twice-exceptional-overview', label: '2E \u2192 Overview', keywords: 'twice exceptional 2e overview introduction what is definition prevalence statistics gifted plus disability dual exceptionality paradox contradiction masking compensating strengths hiding weaknesses weaknesses hiding strengths three subgroups identified gifted identified disability neither identified' },
  { id: 'twice-exceptional-symptoms', label: '2E \u2192 Characteristics', keywords: 'twice exceptional 2e symptoms characteristics traits signs uneven profile asynchronous development high ability some areas difficulty others inconsistent performance brilliant but struggling frustration perfectionism anxiety low self esteem behavioral issues boredom disengagement acting out shutting down sophisticated vocabulary poor handwriting creative thinker poor test taker' },
  { id: 'twice-exceptional-causes', label: '2E \u2192 Causes', keywords: 'twice exceptional 2e causes why both gifted disability genetics brain wiring neurodevelopmental co-occurrence overlap comorbidity' },
  { id: 'twice-exceptional-diagnosis', label: '2E \u2192 Diagnosis', keywords: 'twice exceptional 2e diagnosis identification assessment challenging difficult missed masking compensation average scores hiding both giftedness disability comprehensive evaluation neuropsychological testing iq achievement discrepancy strength weakness pattern who diagnoses qualified evaluator experienced 2e' },
  { id: 'twice-exceptional-support', label: '2E \u2192 Support', keywords: 'twice exceptional 2e support treatment intervention strength based approach nurture gifts address challenges accommodation enrichment simultaneously both challenge support iep gifted plan individualized differentiation mentorship assistive technology social emotional counseling self understanding identity' },
  { id: 'twice-exceptional-living', label: '2E \u2192 Living as 2E', keywords: 'twice exceptional 2e living daily life coping strategies self advocacy identity understanding strengths challenges imposter syndrome belonging community finding tribe self acceptance self compassion career college transition adults children teens' },

  // ============================================================
  // APD - Main + Sub-pages
  // ============================================================
  { id: 'apd', label: 'Auditory Processing Disorder (APD)', keywords: 'auditory processing disorder apd hearing listening sound discrimination central cant hear properly sounds muffled trouble understanding speech background noise noisy classroom following directions mishearing words' },
  { id: 'apd-overview', label: 'APD \u2192 Overview', keywords: 'apd overview introduction what is auditory processing disorder central hearing normal audiogram brain processing sound types deficit decoding tolerance integration prosodic' },
  { id: 'apd-symptoms', label: 'APD \u2192 Symptoms', keywords: 'apd symptoms signs difficulty hearing in noise background noise cocktail party mishearing words sounds similar confusing following multi step directions slow processing auditory information asking huh what repeat frequently favoring one ear reading difficulty spelling difficulty distractible by sounds noise sensitivity fatigue listening effort' },
  { id: 'apd-causes', label: 'APD \u2192 Causes', keywords: 'apd causes risk factors ear infections chronic otitis media neurological brain auditory pathway maturation delay genetics premature birth head injury meningitis' },
  { id: 'apd-diagnosis', label: 'APD \u2192 Diagnosis', keywords: 'apd diagnosis assessment evaluation testing audiologist audiology central auditory processing battery dichotic listening gap detection speech in noise temporal processing normal hearing required age typically 7 or older' },
  { id: 'apd-support', label: 'APD \u2192 Support & Treatment', keywords: 'apd support treatment intervention fm system remote microphone roger system classroom acoustics preferential seating noise reduction visual supports written instructions auditory training therapy speech language therapy compensatory strategies self advocacy accommodation iep 504' },
  { id: 'apd-living', label: 'APD \u2192 Living with APD', keywords: 'apd living daily life coping strategies hearing in noise restaurants meetings workplace accommodation technology fm system captions subtitles quiet environment communication strategies asking for repeats self advocacy adults children teens' },

  // ============================================================
  // VISUAL PROCESSING DISORDER - Main + Sub-pages
  // ============================================================
  { id: 'visual-processing', label: 'Visual Processing Disorder', keywords: 'visual processing disorder vpd vision perception spatial tracking trouble seeing reading skipping lines losing place blurry depth perception hand eye coordination irlen syndrome colored overlays vision therapy' },
  { id: 'visual-processing-overview', label: 'VPD \u2192 Overview', keywords: 'visual processing disorder overview introduction what is visual perception brain processing not eye problem normal eye exam types visual discrimination figure ground closure memory spatial motor integration' },
  { id: 'visual-processing-symptoms', label: 'VPD \u2192 Symptoms', keywords: 'visual processing symptoms signs skipping lines rereading losing place words move blur reversals confusing similar looking letters difficulty copying board puzzles mazes depth perception clumsiness bumping into things difficulty catching throwing ball messy handwriting spacing alignment' },
  { id: 'visual-processing-causes', label: 'VPD \u2192 Causes', keywords: 'visual processing causes risk factors brain visual cortex occipital parietal dorsal ventral stream neurological development genetics head injury' },
  { id: 'visual-processing-diagnosis', label: 'VPD \u2192 Diagnosis', keywords: 'visual processing diagnosis assessment evaluation testing developmental optometrist behavioral optometrist vision therapy evaluation eye tracking convergence accommodation visual perceptual testing occupational therapy evaluation beery vmi tvps mvpt' },
  { id: 'visual-processing-support', label: 'VPD \u2192 Support & Treatment', keywords: 'visual processing support treatment intervention vision therapy optometric exercises eye tracking training colored overlays tinted lenses irlen large print modified worksheets visual guides rulers line trackers occupational therapy accommodation school iep 504' },
  { id: 'visual-processing-living', label: 'VPD \u2192 Living with VPD', keywords: 'visual processing living daily life coping strategies reading tools text formatting large font high contrast visual aids organization color coding technology screen settings accessibility self advocacy adults children teens' },

  // ============================================================
  // SPD - Main + Sub-pages
  // ============================================================
  { id: 'spd', label: 'Sensory Processing Disorder (SPD)', keywords: 'sensory processing disorder spd sensitivities overresponsive underresponsive integration sensory overload overwhelmed too loud too bright tags clothing textures food picky eater weighted blanket fidget meltdown shutdown regulation' },
  { id: 'spd-overview', label: 'SPD \u2192 Overview', keywords: 'spd overview introduction what is sensory processing disorder subtypes sensory modulation disorder sensory based motor disorder sensory discrimination disorder over responsive under responsive seeking craving eight senses visual auditory tactile gustatory olfactory vestibular proprioception interoception' },
  { id: 'spd-symptoms', label: 'SPD \u2192 Symptoms', keywords: 'spd symptoms signs over responsive hypersensitive avoidant noise sensitivity light sensitivity touch aversion clothing tags seams textures food selectivity picky eater gag smell overwhelmed meltdown anxiety fear avoidance under responsive hyposensitive seeking crashing jumping spinning climbing rough play high pain tolerance doesnt notice temperature hunger bathroom sensory seeking fidgeting chewing mouthy touching everything constant movement discrimination difficulty telling similar sounds apart similar textures identifying body signals' },
  { id: 'spd-causes', label: 'SPD \u2192 Causes', keywords: 'spd causes risk factors genetics brain sensory integration neurological development premature birth nicu institutionalization early deprivation prenatal exposure environmental co-occurring autism adhd anxiety' },
  { id: 'spd-diagnosis', label: 'SPD \u2192 Diagnosis', keywords: 'spd diagnosis assessment evaluation sensory profile sensory processing measure occupational therapist clinical observation parent report teacher report standardized assessment not in dsm controversial recognition validated by research' },
  { id: 'spd-support', label: 'SPD \u2192 Support & Treatment', keywords: 'spd support treatment intervention occupational therapy sensory integration therapy ot sensory diet alerting calming heavy work proprioceptive vestibular activities environmental modifications classroom home workplace noise reduction lighting fidget tools weighted blanket compression vest chewelry noise cancelling headphones wilbarger brushing protocol therapeutic listening zone of regulation alert program accommodation iep 504' },
  { id: 'spd-living', label: 'SPD \u2192 Living with SPD', keywords: 'spd living daily life coping strategies sensory toolkit bag emergency kit environment design home school workplace clothing comfortable dressing routine food expanding diet safe foods mealtimes self regulation strategies zones engine levels body signals calming corner safe space decompression time breaks social situations planning ahead energy management adults children teens families' },

  // ============================================================
  // CONDITIONS WITHOUT SUB-PAGES (enhanced keywords)
  // ============================================================
  { id: 'misophonia', label: 'Misophonia', keywords: 'misophonia sound sensitivity trigger sounds chewing anger rage selective sound eating sounds mouth sounds breathing sniffling tapping clicking pen keyboard typing triggered by sounds fight or flight anger irritation anxiety disgust noise cancelling headphones earplugs white noise coping avoidance accommodation relationships family dinner' },
  { id: 'synesthesia', label: 'Synesthesia', keywords: 'synesthesia senses colors sounds cross-modal perception seeing sounds hearing colors tasting words number color letter color chromesthesia grapheme spatial sequence mirror touch smell taste music art creativity automatic involuntary' },
  { id: 'dyspraxia', label: 'Dyspraxia (DCD)', keywords: 'dyspraxia dcd developmental coordination disorder motor planning clumsy movement awkward coordination balance tripping falling bumping dropping handwriting sports riding bike tying shoes buttons zippers fine motor gross motor occupational therapy physical therapy apraxia sequencing organization spatial body awareness proprioception' },
  { id: 'tourette', label: 'Tourette Syndrome', keywords: 'tourette tics motor vocal involuntary movements sounds eye blinking throat clearing sniffing head jerking shoulder shrugging coprolalia echolalia complex simple waxing waning premonitory urge suppression tic attack cbit habit reversal medication clonidine guanfacine comorbid adhd ocd anxiety' },
  { id: 'ocd', label: 'OCD', keywords: 'ocd obsessive compulsive disorder intrusive thoughts rituals anxiety obsessions compulsions contamination germs washing hands checking counting symmetry ordering harm thoughts unwanted thoughts pure o mental rituals reassurance seeking doubt perfectionism scrupulosity hoarding erp exposure response prevention cbt ssri serotonin' },
  { id: 'bipolar', label: 'Bipolar Disorder', keywords: 'bipolar disorder mania depression mood swings manic episodes cycling bipolar 1 bipolar 2 hypomania mixed episodes rapid cycling mood stabilizer lithium lamotrigine medication energy sleep grandiosity impulsive spending risky behavior depressive hopeless suicidal psychosis racing thoughts' },
  { id: 'schizophrenia', label: 'Schizophrenia', keywords: 'schizophrenia psychosis hallucinations delusions thought disorder hearing voices paranoia disorganized thinking flat affect negative positive cognitive symptoms antipsychotic medication social withdrawal isolation reality schizoaffective early intervention first episode prodromal' },
  { id: 'downsyndrome', label: 'Down Syndrome', keywords: 'down syndrome trisomy 21 chromosome intellectual developmental genetic cognitive delay speech language heart defect health screening prenatal karyotype mosaic translocation early intervention therapy inclusion education iep adaptive skills independence' },
  { id: 'intellectual-disability', label: 'Intellectual Disability', keywords: 'intellectual disability cognitive developmental adaptive functioning iq learning difficulties daily living communication self care social skills mild moderate severe profound support needs special education iep transition vocational independence community adaptive behavior' },
  { id: 'fasd', label: 'Fetal Alcohol Spectrum Disorder (FASD)', keywords: 'fasd fetal alcohol spectrum disorder prenatal exposure fas fetal alcohol syndrome birth defects facial features growth learning behavior memory attention executive function adaptive social impulse control maternal drinking pregnancy prevention' },
  { id: 'epilepsy', label: 'Epilepsy', keywords: 'epilepsy seizures neurological convulsions brain electrical seizure disorder absence tonic clonic grand mal focal partial generalized status epilepticus eeg anticonvulsant medication keppra lamictal depakote surgery vns ketogenic diet trigger flashing lights first aid safety driving' },
  { id: 'tbi', label: 'TBI (Traumatic Brain Injury)', keywords: 'tbi traumatic brain injury concussion head trauma acquired mild moderate severe closed head skull fracture cognitive impairment memory attention headache dizziness balance rehabilitation neuropsychology occupational physical speech therapy post concussion syndrome recovery falls accidents sports military veterans' },
  { id: 'cte', label: 'CTE (Chronic Traumatic Encephalopathy)', keywords: 'cte chronic traumatic encephalopathy concussion sports head injury degenerative repeated impacts subconcussive tau protein brain degeneration football boxing hockey rugby mood behavior memory cognitive decline aggression depression dementia autopsy prevention helmet safety' },
  { id: 'pandas', label: 'PANDAS', keywords: 'pandas autoimmune streptococcal neuropsychiatric pediatric ocd tics infection brain inflammation pans strep throat sudden onset overnight behavior anxiety separation regression antibiotics ivig plasmapheresis immunotherapy controversial basal ganglia autoantibodies' },
];
